version: '2'
services:
#  php8.0:
#    container_name: php8.0
#    build:
#      context: ./dockerfiles/php-fpm/php8.0
#      dockerfile: Dockerfile
#    #    image: joseluisq/php-fpm:8.1.4
#    environment:
#      - "ENV_SUBSTITUTION_ENABLE=true"
#      - "PHP_MEMORY_LIMIT=512M"
#      - "PHP_DISPLAY_ERRORS=On"
#      - "PHP_FPM_LISTEN=9000"
#      - "PHP_SESSION_GC_MAXLIFETIME=7200"
#    expose:
#      - "9000"
#    volumes:
#      - /var/www/html:/var/www/html
#      - ./dockerfiles/php-fpm/php8.0/php.ini:/var/data/php-fpm/default-php.tmpl.ini
#    networks:
#      my_external_network:
#        ipv4_address: 20.5.0.9
#    depends_on:
#      - mysql
#      - maildev
  php8.2:
    container_name: php8.2
    build:
      context: ./dockerfiles/php-fpm/php8.2
      dockerfile: Dockerfile
    environment:
      - "ENV_SUBSTITUTION_ENABLE=true"
      - "PHP_MEMORY_LIMIT=512M"
      - "PHP_DISPLAY_ERRORS=On"
      - "PHP_FPM_LISTEN=9000"
      - "PHP_SESSION_GC_MAXLIFETIME=7200"
    expose:
      - "9000"
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - ./dockerfiles/php-fpm/php8.2/php.ini:/var/data/php-fpm/default-php.tmpl.ini
    networks:
      my_external_network:
        ipv4_address: 172.19.0.6
    depends_on:
      - mysql
      - maildev
  php7:
    build:
      context: ./dockerfiles/php-fpm/php-7.4
      dockerfile: Dockerfile
    container_name: php7.4
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - ./dockerfiles/php-fpm/php-7.4/php.ini:/usr/local/etc/php/php.ini
#      - ./dockerfiles/php-fpm/php-7.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      my_external_network:
        ipv4_address: 172.19.0.9
    depends_on:
      - mysql
      - maildev
#
##  php5:
##    build:
##      context: ./dockerfiles/php-fpm/php5-6
##      dockerfile: Dockerfile
##    container_name: php5
##    volumes:
##      - /var/www/html:/var/www/html
##      - ./dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
##    networks:
##      vpcbr:
##        ipv4_address: 20.5.0.5
##    depends_on:
##      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/html:/var/www/html
      - ./dockerfiles/nginx:/etc/nginx/conf.d
      - ./dockerfiles/nginx/htpasswd/:/etc/nginx/htpasswd
      - /var/www/html/letsencrypt/certbot/conf:/etc/nginx/ssl/:ro
    networks:
      my_external_network:
        ipv4_address: 172.19.0.5
    depends_on:
      - php8.2
      - php7

  mysql:
    container_name: mysql5
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./dockerfiles/mysql5/lib:/var/lib/mysql
    networks:
      my_external_network:
        ipv4_address: 172.19.0.7
    environment:
      MYSQL_ROOT_PASSWORD: oceanys
      MYSQL_USER: raouf
      MYSQL_PASSWORD: raouf
      MYSQL_DATABASE: symfony

  maildev:
    image: maildev/maildev:${MAILDEV_VERSION:-latest}
    container_name: "maildev"
    restart: always
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - "1080:1080"
    networks:
      my_external_network:
        ipv4_address: 172.19.0.8

#  mailcatcher:
#    image: schickling/mailcatcher
#    container_name: mailcatcher
#    ports:
#      - "1080:1080"
#      - "1025:1025"
#    networks:
#      vpcbr:
#        ipv4_address: 20.5.0.7

#  node:
#    container_name: node
#    build:
#      context: ./dockerfiles/node
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
networks:
  my_external_network:
    external: true
#networks:
#  vpcbr:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 20.5.0.0/16
#          gateway: 20.5.0.1
