version: '2'
services:
#  php8:
#    build:
#      context: ./dockerfiles/php-fpm/php8.1
#      dockerfile: Dockerfile
##    image: joseluisq/php-fpm:8.1.4
#    container_name: php8.1
#    environment:
#      - "ENV_SUBSTITUTION_ENABLE=true"
#      - "PHP_MEMORY_LIMIT=512M"
#      - "PHP_DISPLAY_ERRORS=On"
#      - "PHP_FPM_LISTEN=9000"
#      - "PHP_SESSION_GC_MAXLIFETIME=7200"
#    expose:
#      - "9000"
#    volumes:
#      - /var/www/html:/var/www/html
#      - ./dockerfiles/php-fpm/php8.1/php.ini:/var/data/php-fpm/default-php.tmpl.ini
#    networks:
#      vpcbr:
#        ipv4_address: 20.5.0.8
#    depends_on:
#      - mysql
#      - mailcatcher
  php7:
    build:
      context: ./dockerfiles/php-fpm/php-7.4
      dockerfile: Dockerfile
    container_name: php7.4
    volumes:
      - /var/www/html:/var/www/html
      - ./dockerfiles/php-fpm/php-7.4/php.ini:/usr/local/etc/php/php.ini
      - ./dockerfiles/php-fpm/php-7.4/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      vpcbr:
        ipv4_address: 20.5.0.2
    depends_on:
      - mysql
      - maildev

#  php5:
#    build:
#      context: ./dockerfiles/php-fpm/php5-6
#      dockerfile: Dockerfile
#    container_name: php5
#    volumes:
#      - /var/www/html:/var/www/html
#      - ./dockerfiles/php-fpm/php.ini:/usr/local/etc/php/php.ini
#    networks:
#      vpcbr:
#        ipv4_address: 20.5.0.5
#    depends_on:
#      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    networks:
      vpcbr:
        ipv4_address: 20.5.0.3
    depends_on:
#      - php8
      - php7
  mysql:
    container_name: mysql5
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./dockerfiles/mysql/lib:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 20.5.0.4
    environment:
      MYSQL_ROOT_PASSWORD: oceanys
      MYSQL_USER: raouf
      MYSQL_PASSWORD: raouf
      MYSQL_DATABASE: symfony

  maildev:
    image: maildev/maildev:${MAILDEV_VERSION:-latest}
    container_name: "maildev"
    restart: unless-stopped
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - "1080:1080"
    networks:
      vpcbr:
        ipv4_address: 20.5.0.7

#  mailcatcher:
#    image: schickling/mailcatcher
#    container_name: mailcatcher
#    ports:
#      - "1080:1080"
#      - "1025:1025"
#    networks:
#      vpcbr:
#        ipv4_address: 20.5.0.7

#  node:
#    container_name: node
#    build:
#      context: ./dockerfiles/node
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 20.5.0.0/16
          gateway: 20.5.0.1
